-- ============================================================================
-- SEED DE DEMONSTRAÇÃO — SINTERA (aplicação manual)
-- ============================================================================
-- Fonte única do conteúdo = função public.seed_demo() (migration 121). Este arquivo é só o atalho manual.
--
-- REPRODUZÍVEL (recomendado): rode o runner que cria o usuário + popula tudo com um comando:
--     npm run seed:demo
--   (requer NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY no ambiente; NUNCA commitar o service key)
--
-- MANUAL (se preferir): 1) crie demo@sintera.app no painel Supabase (Auth → Add user, Auto Confirm);
--   2) rode no SQL editor:
select public.seed_demo();  -- idempotente; recria os dados fictícios do usuário demo@sintera.app
-- ============================================================================
